PLUGIN=$(shell basename `pwd`)
PROJ_ROOT=$(shell dirname `pwd`)
OBJ_DIR=bin
SRC_DIR=src
API=../include/mcpc-api.jar
JAR=$(PLUGIN).jar

include sources.mk

SRCS_FULL=$(addprefix $(SRC_DIR)/,$(SRCS))

JAVACFLAGS = -d $(OBJ_DIR) -cp $(API)

$(JAR): $(SRCS_FULL)
	mkdir -p $(OBJ_DIR)
	javac $(JAVACFLAGS) $(SRCS_FULL)
	cp plugin.yml $(OBJ_DIR)
	cd $(OBJ_DIR) && jar cvf $(PROJ_ROOT)/$(JAR) *

clean:
	rm -rf bin
	rm -f $(JAR)
