name: Nethrar
author: Andrew Krieger
description: Portals, now with minecart support!
version: 3.0-alpha1
main: org.akrieger.Nethrar.Nethrar
commands:
    nethrar:
        description: Accesses Nethrar functionality.
        usage: |
            /nethrar tp world
